export const WISHLIST_REQUESTING = 'WISHLIST_REQUESTING';
export const WISHLIST_REQUESTED = 'WISHLIST_REQUESTED'; 
export const WISHLIST_REQUESTERROR = 'WISHLIST_REQUESTERROR';

export const DELFROMWISH_REQUESTING = 'DELFROMWISH_REQUESTING';
export const DELFROMWISH_REQUESTED = 'DELFROMWISH_REQUESTED'; 
export const DELFROMWISH_REQUESTERROR = 'DELFROMWISH_REQUESTERROR';

