export const  SPINNER = "SPINNER";
export const  CLOSESPINNER = "CLOSESPINNER";
// export const GETUSERINFORMATION_RQUESTING = 'GETUSERINFORMATION_RQUESTING'
// export const GETUSERINFORMATION_RQUESTED = 'GETUSERINFORMATION_RQUESTED'
// export const GETUSERINFORMATION_RQUESTERROR = 'GETUSERINFORMATION_RQUESTERROR'
