export const List_REQUESTING = 'List_REQUESTING'
export const List_REQUESTED = 'List_REQUESTED'
export const List_REQUESTERROR = 'List_REQUESTERROR'

export const ListBRAND_REQUESTING = 'ListBRAND_REQUESTING'
export const ListBRAND_REQUESTED = 'ListBRAND_REQUESTED'
export const ListBRAND_REQUESTERROR = 'ListBRAND_REQUESTERROR'

export const STAR_REQUESTING =  'STAR_REQUESTING'
export const STAR_REQUESTED =  'STAR_REQUESTED'
export const STAR_REQUESTERROR =  'STAR_REQUESTERROR'

export const setSTAR_REQUESTING =  'setSTAR_REQUESTING'
export const setSTAR_REQUESTED =  'setSTAR_REQUESTED'
export const setSTAR_REQUESTERROR =  'setSTAR_REQUESTERROR'