export const GETHOT_REQUESTING = 'GETHOT_REQUESTING';
export const GETHOT_REQUESTED = 'GETHOT_REQUESTED';
export const GETHOT_REQUESTERROR = 'GETHOT_REQUESTERROR';


export const GETOFF_REQUESTING = 'GETOFF_REQUESTING';
export const GETOFF_REQUESTED = 'GETOFF_REQUESTED';
export const GETOFF_REQUESTERROR = 'GETOFF_REQUESTERROR';

export const GETYSL_REQUESTING = 'GETYSL_REQUESTING';
export const GETYSL_REQUESTED = 'GETYSL_REQUESTED';
export const GETYSL_REQUESTERROR = 'GETYSL_REQUESTERROR';

export const GETGUCCI_REQUESTING = 'GETGUCCI_REQUESTING';
export const GETGUCCI_REQUESTED = 'GETGUCCI_REQUESTED';
export const GETGUCCI_REQUESTERROR = 'GETGUCCI_REQUESTERROR';

export const GETOTHER_REQUESTING = 'GETOTHER_REQUESTING';
export const GETOTHER_REQUESTED = 'GETOTHER_REQUESTED';
export const GETOTHER_REQUESTERROR = 'GETOTHER_REQUESTERROR';